apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
stringData:
  MQTT_USERNAME: '{{`{{ .MOSQUITTO_USERNAME }}`}}'
  MQTT_PASSWORD: '{{`{{ .MOSQUITTO_PASSWORD }}`}}'
  USB_DEVICES_URL: '{{`{{ .USB_DEVICES_URL }}`}}'
  