name: Build and push Zigbee2MQTT1

on:
  push:
    # paths-ignore:
    #   - "README.md"
  workflow_dispatch:

jobs:
  package_helm:
    runs-on: ubuntu-22.04
    name: Package helm chart
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        uses: jonaskop/custom-github-actions/get-version@main

      - name: Build container image
        uses: jonaskop/custom-github-actions/build-container-image@main
        with:
          image: zigbee2mqtt
          tag: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        uses: jonaskop/custom-github-actions/package-helm-chart@main
        with:
          chart: helm/zigbee2mqtt
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        if: github.ref_name == 'main'
        uses: jonaskop/custom-github-actions/set-version@main
        with:
          version: ${{ env.VERSION }}
